CREATE DATABASE IF NOT EXISTS puzzleGame;
USE puzzleGame;

-- Create Database
CREATE DATABASE IF NOT EXISTS puzzleGame;
USE puzzleGame;

-- Table: User
CREATE TABLE IF NOT EXISTS User (
  userId BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL
);

-- Table: GameState
CREATE TABLE IF NOT EXISTS GameState (
  gameStateId BIGINT AUTO_INCREMENT PRIMARY KEY,
  userId BIGINT NOT NULL,
  moveCount INT NOT NULL,
  gridSize INT NOT NULL,
  isCompleted BOOLEAN NOT NULL,
  boardStateJson TEXT NOT NULL,
  FOREIGN KEY (userId) REFERENCES User(userId)
);

-- Table: Image
CREATE TABLE IF NOT EXISTS Image (
  imageId BIGINT AUTO_INCREMENT PRIMARY KEY,
  filePath VARCHAR(255) NOT NULL,
  userId BIGINT NOT NULL,
  FOREIGN KEY (userId) REFERENCES User(userId)
);
